version: '2.1's
services:
  localstack:
    image: localstack/localstack-full
    ports:
      - "4566:4566"
      - "8080:8080"
    environment:
      - SERVICES=s3
      - LAMBDA_EXECUTOR=local
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"