service: tooling-s3-sqs
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  state: ${opt:stage, "dev"}
  environment:
    BUCKET_NAME: arquivos-009-vagner 
    SQS_QUEUE: file-handler
  iamRoleStatements: 
    - Effect: Allow
      Action:
        - sqs:SendMessage
        - sqs:GetQueueUrl
        - sqs:CreateQueue
        - sqs:ReceiveMessage
      Resource: ${self.custom.sqsArn}
    - Effect: Allow
      Action:
        - s3:*
      Resource: 
        - arn:aws:s3:::${self:provider.environment.BUCKET_NAME}/*
        - arn:aws:s3:::${self:provider.environment.BUCKET_NAME}

plugins: 
  - serverless-mocha-plugin
  - serverless-offline

custom:
  sqsArn:
    Fn::GetAtt:
      - SQSQueue
      - Arn

  localstack:
    stages:
      - local
    # desabilitar o localstack quando fizer deploy  
    autostart: false
    
  serverless-offline:
    userChildProcesses: true

packages: 
  individually: true
  excludeDevDependencies: true

functions:
  s3listener:
    handler: src/index.s3listener
    events:
      - s3:
          bucket: ${self:provider.environment.BUCKET_NAME}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .csv

  sqslistener:
    handler: src/index.sqslistener
    events:
      - sqs:
          batchSize: 1
          arn: ${self:custom.sqsArn}

resources: 
  Resources:
    SQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:provider.environment.SQS_QUEUE}
        VisibilityTimeout: 60

        
 